import { Tag, MaterialWithTags } from '@/types'

export const MOCK_TAGS: Tag[] = [
  // Scene
  { id: 's1', name: '品牌', slug: 'brand', dimension: 'scene', color: '#FF2442' },
  { id: 's2', name: '运营', slug: 'operation', dimension: 'scene', color: '#FF6B6B' },
  { id: 's3', name: '包装', slug: 'packaging', dimension: 'scene', color: '#FF8E53' },
  { id: 's4', name: '多媒体', slug: 'multimedia', dimension: 'scene', color: '#C44EFF' },
  { id: 's5', name: '衍生品', slug: 'merchandise', dimension: 'scene', color: '#FF4EA0' },
  // Style
  { id: 'st1', name: '极简高级', slug: 'minimal', dimension: 'style', color: '#1A1A1A' },
  { id: 'st2', name: '拼贴', slug: 'collage', dimension: 'style', color: '#FF9F43' },
  { id: 'st3', name: '插画', slug: 'illustration', dimension: 'style', color: '#48DBFB' },
  { id: 'st4', name: '3D', slug: '3d', dimension: 'style', color: '#0ABDE3' },
  { id: 'st5', name: '复古', slug: 'retro', dimension: 'style', color: '#F9CA24' },
  { id: 'st6', name: '怪诞超现实', slug: 'surreal', dimension: 'style', color: '#6C5CE7' },
  { id: 'st7', name: '时髦', slug: 'chic', dimension: 'style', color: '#FD79A8' },
  { id: 'st8', name: '年轻前卫', slug: 'avant-garde', dimension: 'style', color: '#00B894' },
  // Element
  { id: 'e1', name: '排版字体', slug: 'typography', dimension: 'element', color: '#636E72' },
  { id: 'e2', name: '色彩搭配', slug: 'color', dimension: 'element', color: '#FDCB6E' },
  { id: 'e3', name: '插画', slug: 'illustration-el', dimension: 'element', color: '#74B9FF' },
  { id: 'e4', name: '摄影', slug: 'photography', dimension: 'element', color: '#55EFC4' },
  { id: 'e5', name: '拼贴', slug: 'collage-el', dimension: 'element', color: '#A29BFE' },
  { id: 'e6', name: '3D', slug: '3d-el', dimension: 'element', color: '#81ECEC' },
]

const unsplashImages = [
  { url: 'https://images.unsplash.com/photo-1634733988138-bf2c3a2a13fa?w=800&q=80', h: 600 },
  { url: 'https://images.unsplash.com/photo-1586880244406-556ebe35f282?w=800&q=80', h: 500 },
  { url: 'https://images.unsplash.com/photo-1633354931133-27b1a9b3f5b3?w=600&q=80', h: 700 },
  { url: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=600&q=80', h: 450 },
  { url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80', h: 600 },
  { url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=600&q=80', h: 800 },
  { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', h: 530 },
  { url: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&q=80', h: 480 },
  { url: 'https://images.unsplash.com/photo-1604871000636-074fa5117945?w=800&q=80', h: 650 },
  { url: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80', h: 550 },
  { url: 'https://images.unsplash.com/photo-1579547621113-e4bb2a19bdd6?w=800&q=80', h: 400 },
  { url: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80', h: 700 },
  { url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80', h: 600 },
  { url: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80', h: 450 },
  { url: 'https://images.unsplash.com/photo-1636955816868-fcb881e57954?w=800&q=80', h: 750 },
  { url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&q=80', h: 500 },
  { url: 'https://images.unsplash.com/photo-1618004652321-13a63e576b80?w=800&q=80', h: 620 },
  { url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80', h: 480 },
]

export const MOCK_MATERIALS: MaterialWithTags[] = [
  {
    id: '1',
    title: '极简品牌视觉',
    description: '干净的白色背景配合精准的排版，高级感扑面而来',
    image_url: unsplashImages[0].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: true,
    created_at: '2024-01-01',
    tags: [MOCK_TAGS[0], MOCK_TAGS[5], MOCK_TAGS[13]],
  },
  {
    id: '2',
    title: '包装设计参考',
    description: '东方美学与现代设计语言的融合',
    image_url: unsplashImages[1].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: true,
    created_at: '2024-01-02',
    tags: [MOCK_TAGS[2], MOCK_TAGS[5], MOCK_TAGS[14]],
  },
  {
    id: '3',
    title: '3D 产品展示',
    description: '立体感十足的产品渲染，视觉冲击力强',
    image_url: unsplashImages[2].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: true,
    created_at: '2024-01-03',
    tags: [MOCK_TAGS[1], MOCK_TAGS[8], MOCK_TAGS[18]],
  },
  {
    id: '4',
    title: '插画风运营海报',
    description: '手绘插画结合活泼色块，年轻有活力',
    image_url: unsplashImages[3].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: false,
    created_at: '2024-01-04',
    tags: [MOCK_TAGS[1], MOCK_TAGS[7], MOCK_TAGS[16]],
  },
  {
    id: '5',
    title: '复古拼贴风格',
    description: '撕纸感与胶片质感叠加，充满年代记忆',
    image_url: unsplashImages[4].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: true,
    created_at: '2024-01-05',
    tags: [MOCK_TAGS[0], MOCK_TAGS[6], MOCK_TAGS[9], MOCK_TAGS[17]],
  },
  {
    id: '6',
    title: '时髦摄影风格',
    description: '高对比度摄影配色，时尚大片质感',
    image_url: unsplashImages[5].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: false,
    created_at: '2024-01-06',
    tags: [MOCK_TAGS[0], MOCK_TAGS[11], MOCK_TAGS[15]],
  },
  {
    id: '7',
    title: '年轻前卫视觉',
    description: '打破常规的构图与色彩搭配，先锋艺术感',
    image_url: unsplashImages[6].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: true,
    created_at: '2024-01-07',
    tags: [MOCK_TAGS[1], MOCK_TAGS[12], MOCK_TAGS[14]],
  },
  {
    id: '8',
    title: '衍生品设计展示',
    description: '品牌衍生品的高质感陈列拍摄风格',
    image_url: unsplashImages[7].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: false,
    created_at: '2024-01-08',
    tags: [MOCK_TAGS[4], MOCK_TAGS[5], MOCK_TAGS[15]],
  },
  {
    id: '9',
    title: '怪诞超现实合成',
    description: '天马行空的视觉创意，超现实主义的视觉表达',
    image_url: unsplashImages[8].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: true,
    created_at: '2024-01-09',
    tags: [MOCK_TAGS[0], MOCK_TAGS[10], MOCK_TAGS[17]],
  },
  {
    id: '10',
    title: '极简字体排版',
    description: '字体即设计，用排版讲故事',
    image_url: unsplashImages[9].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: false,
    created_at: '2024-01-10',
    tags: [MOCK_TAGS[5], MOCK_TAGS[13]],
  },
  {
    id: '11',
    title: '色彩搭配参考',
    description: '和谐又大胆的色彩系统，奠定品牌调性',
    image_url: unsplashImages[10].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: false,
    created_at: '2024-01-11',
    tags: [MOCK_TAGS[0], MOCK_TAGS[14]],
  },
  {
    id: '12',
    title: '多媒体动态视觉',
    description: '适合短视频的视觉语言与动态感',
    image_url: unsplashImages[11].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: true,
    created_at: '2024-01-12',
    tags: [MOCK_TAGS[3], MOCK_TAGS[12], MOCK_TAGS[14]],
  },
  {
    id: '13',
    title: '品牌全套 VI',
    description: '系统化的品牌视觉识别体系',
    image_url: unsplashImages[12].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: false,
    created_at: '2024-01-13',
    tags: [MOCK_TAGS[0], MOCK_TAGS[5], MOCK_TAGS[13]],
  },
  {
    id: '14',
    title: '食品包装设计',
    description: '清新自然的食品类包装设计参考',
    image_url: unsplashImages[13].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: false,
    created_at: '2024-01-14',
    tags: [MOCK_TAGS[2], MOCK_TAGS[7], MOCK_TAGS[15]],
  },
  {
    id: '15',
    title: '3D 字体设计',
    description: '立体字在海报中的应用参考',
    image_url: unsplashImages[14].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: true,
    created_at: '2024-01-15',
    tags: [MOCK_TAGS[1], MOCK_TAGS[8], MOCK_TAGS[13], MOCK_TAGS[18]],
  },
  {
    id: '16',
    title: '复古海报风格',
    description: '70-80年代复古印刷风格的现代演绎',
    image_url: unsplashImages[15].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: false,
    created_at: '2024-01-16',
    tags: [MOCK_TAGS[1], MOCK_TAGS[9], MOCK_TAGS[17]],
  },
  {
    id: '17',
    title: '插画品牌形象',
    description: '可爱插画风格的品牌视觉呈现',
    image_url: unsplashImages[16].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: false,
    created_at: '2024-01-17',
    tags: [MOCK_TAGS[0], MOCK_TAGS[7], MOCK_TAGS[16]],
  },
  {
    id: '18',
    title: '运营活动页面',
    description: '促销活动的视觉层次与信息架构',
    image_url: unsplashImages[17].url,
    source_url: 'https://unsplash.com',
    source_platform: 'Unsplash',
    is_featured: true,
    created_at: '2024-01-18',
    tags: [MOCK_TAGS[1], MOCK_TAGS[11], MOCK_TAGS[14]],
  },
]
